version: '3.9'
services:
  db:
    image: postgres:16
    container_name: mas-db
    environment:
      POSTGRES_USER: mas
      POSTGRES_PASSWORD: mas
      POSTGRES_DB: mas
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mas"]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:7
    container_name: mas-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  meili:
    image: getmeili/meilisearch:v1.7
    container_name: mas-meili
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7700/health"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  db_data:

